#version: '3.8'
#
#services:
#  spring-app:
#    image: spring-security-jwt
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/cms
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#
#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234
#      MYSQL_DATABASE: cms
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 1234
#    ports:
#      - "3307:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#
#volumes:
#  db_data:
